"""Analytics feature package."""
from fastapi import APIRouter
from . import analytics, bi, reports, financial_reports, pnl, cashflow, cashflow_prediction, balance_sheet, forecasting, kpi_goals, mobile_kpi, budget, scenario_planning, cohort_analysis, anomaly_detection, anomaly_notifications, dashboard_builder, report_builder, excel_reports, statement_requests, ceo_dashboard, churn_dashboard, ledger, vat_return, zakat, zatca, accounting

router = APIRouter()
router.include_router(analytics.router)
router.include_router(bi.router)
router.include_router(reports.router)
router.include_router(financial_reports.router)
router.include_router(pnl.router)
router.include_router(cashflow.router)
router.include_router(cashflow_prediction.router)
router.include_router(balance_sheet.router)
router.include_router(forecasting.router)
router.include_router(kpi_goals.router)
router.include_router(mobile_kpi.router)
router.include_router(budget.router)
router.include_router(scenario_planning.router)
router.include_router(cohort_analysis.router)
router.include_router(anomaly_detection.router)
router.include_router(anomaly_notifications.router)
router.include_router(dashboard_builder.router)
router.include_router(report_builder.router)
router.include_router(excel_reports.router)
router.include_router(statement_requests.router)
router.include_router(ceo_dashboard.router)
router.include_router(churn_dashboard.router)
router.include_router(ledger.router)
router.include_router(vat_return.router)
router.include_router(zakat.router)
router.include_router(zatca.router)
router.include_router(accounting.router)
from . import activity, board_packs, market_expansion, pricing_experiments, widget
router.include_router(activity.router)
router.include_router(board_packs.router)
router.include_router(market_expansion.router)
router.include_router(pricing_experiments.router)
router.include_router(widget.router)
