"""audit_log: add tamper-evident hash-chain columns (SOC 2)

Revision ID: b3c4d5e6f7a8
Revises: 18297a0d0082
Create Date: 2026-07-06

services/audit_chain.py (verify/export endpoints under
/api/compliance/audit-chain) shipped expecting sequence_no / previous_hash /
row_hash on audit_log, but the columns were never migrated — both endpoints
500'd on every call. Legacy rows get genesis hashes ("0"*64), which the
verifier already treats as unchained-but-valid.
"""
from alembic import op
import sqlalchemy as sa

revision = "b3c4d5e6f7a8"
down_revision = "18297a0d0082"
branch_labels = None
depends_on = None

GENESIS = "0" * 64


def upgrade() -> None:
    # BIGINT IDENTITY gives a stable, monotonically increasing global order.
    op.execute(
        "ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS sequence_no BIGINT "
        "GENERATED BY DEFAULT AS IDENTITY UNIQUE"
    )
    op.execute(
        f"ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS previous_hash VARCHAR(64) "
        f"NOT NULL DEFAULT '{GENESIS}'"
    )
    op.execute(
        f"ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS row_hash VARCHAR(64) "
        f"NOT NULL DEFAULT '{GENESIS}'"
    )


def downgrade() -> None:
    op.drop_column("audit_log", "row_hash")
    op.drop_column("audit_log", "previous_hash")
    op.drop_column("audit_log", "sequence_no")
